name: Deploy Backend to AWS Lambda

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code (코드 가져오기)
      uses: actions/checkout@v3

    - name: Setup Python (파이썬 설치)
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Serverless Framework (서버리스 프레임워크 설치)
      run: npm install -g serverless

    - name: Install Python Dependencies (라이브러리 설치)
      run: |
        pip install -r requirements.txt

    - name: Deploy to AWS Lambda (배포 실행)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALGORITHM: ${{ secrets.ALGORITHM }}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
        REFRESH_TOKEN_EXPIRE_DAYS: ${{ secrets.REFRESH_TOKEN_EXPIRE_DAYS }}
        
      run: serverless deploy